const values=[
{icon:'◈',name:'Тіл',title:'Қазақ тілі',text:'Қазақ тілі — ұлттық ойлау, мәдениет пен тарихи тәжірибені жеткізетін маңызды рухани құрал. Тілді білу — сөздерді білу ғана емес, оның көмегімен өз ойыңды, сезіміңді және дүниетанымыңызды жеткізе алу.',modern:'Бүгін: қазақша сөйлесу, сапалы қазақша контент жасау, жаңа сөз үйрену, цифрлық ортада тілдің қолданысын кеңейту.'},
{icon:'⌂',name:'Отбасы',title:'Отбасы',text:'Отбасы — адамның алғашқы тәрбие алатын, мейірім, жауапкершілік, қамқорлық пен өзара құрметті үйренетін ортасы. Отбасылық дәстүр мен естелік ұрпақтар арасындағы байланысты сақтайды.',modern:'Бүгін: бірге уақыт өткізу, ата-әжемен әңгімелесу, отбасылық дәстүрді жалғастыру, бір-біріне қолдау көрсету.'},
{icon:'✦',name:'Салт-дәстүр',title:'Салт-дәстүр мен әдет-ғұрып',text:'Салт-дәстүр халықты бірлікке, сыйластыққа, қонақжайлыққа, үлкенді құрметтеуге және жақсы мінез-құлыққа тәрбиелейді. Оның мәнін түсіну — дәстүрді жай қайталаудан маңызды.',modern:'Бүгін: дәстүрдің мағынасын зерттеу, оны заманауи форматта түсіндіру, отбасында саналы түрде жалғастыру.'},
{icon:'⌛',name:'Тарих',title:'Тарихи құндылықтар',text:'Тарихи жады халықтың өткен жолын, тұлғаларын, тәжірибесін және маңызды оқиғаларын түсінуге көмектеседі. Өткеннен сабақ алу қазіргі шешімдерге жауапкершілікпен қарауға мүмкіндік береді.',modern:'Бүгін: дереккөзбен жұмыс істеу, тарихи орындарды зерттеу, отбасылық тарихты сақтау, тарихи тұлғаларды тану.'},
{icon:'◎',name:'Руханият',title:'Рухани құндылық',text:'Адалдық, ар-ұят, мейірім, ізгілік, жауапкершілік пен әділдік адамның ішкі мәдениетін қалыптастырады. Рухани құндылық адамның нақты қарым-қатынасы мен ісінен көрінеді.',modern:'Бүгін: уәдеде тұру, әділ болу, өзгеге көмектесу, қателігіңді мойындау және өз әрекетіңе жауап беру.'},
{icon:'♫',name:'Мәдениет',title:'Ұлттық мәдениет',text:'Ұлттық мәдениет — халықтың дүниетанымы, өнері, әдебиеті, музыкасы, тұрмысы және шығармашылық тәжірибесінің кең кеңістігі. Оны тану өз мәдени тамырыңды түсінуге және өзгені құрметтеуге жол ашады.',modern:'Бүгін: музей, театр, көрме, кино, кітап, цифрлық storytelling және заманауи шығармашылық арқылы мәдениетті таныту.'},
{icon:'♧',name:'Өнер',title:'Ұлттық өнер мен мұра',text:'Домбыра, күй, айтыс, қолөнер, зергерлік, ұлттық ойындар мен ою-өрнек — халықтың шығармашылық жадын сақтайтын мұра. Ұлттық өнер өткеннің ғана емес, қазіргі шығармашылықтың да бір бөлігі.',modern:'Бүгін: өнер үйрену, орындау, ұлттық элементтерді дизайн мен цифрлық контентте қолдану.'},
{icon:'⌁',name:'Туған жер',title:'Туған жер мен елге сүйіспеншілік',text:'Туған жер — адамның туған өлкесімен, табиғатымен, адамдарымен, мәдениетімен және естелігімен байланысы. Сүйіспеншілік мақтанумен ғана емес, туған ортаға пайдалы әрекетпен де көрінеді.',modern:'Бүгін: туған өлкені зерттеу, табиғатты қорғау, қоғамдық бастамаларға қатысу, жергілікті мәдениетті таныту.'},
{icon:'◇',name:'Тұрмыс',title:'Ұлттық тағамдар мен тұрмыс',text:'Ұлттық тағам, киім, үй тұрмысы мен күнделікті әдеттер халықтың өмір салты мен тарихи тәжірибесін көрсетеді. Олардың мәнін түсіну мәдениеттің күнделікті өмірдегі көрінісін тануға мүмкіндік береді.',modern:'Бүгін: ұлттық тағамды дайындау тарихын білу, отбасылық рецептерді сақтау, ұлттық элементтерді заманауи өмірмен үйлестіру.'}
];
const dict=[['Аманат','Сеніп тапсырылған жауапкершілік, мұра немесе міндетті сақтап, келесіге жеткізу ұғымы.'],['Құндылық','Адам мен қоғам үшін маңызды мән, ұстаным және мағына.'],['Бірлік','Ортақ мақсатқа жұмылу, өзара түсінісу және татулық.'],['Ынтымақ','Адамдардың өзара қолдауы мен келісімге негізделген бірлесуі.'],['Құрмет','Адамның қадірін, еңбегін, пікірін және мәдениетін бағалау.'],['Ар','Адамның ішкі моральдық өлшемі, адалдық пен жауапкершілікке қатысты ұғым.'],['Мейірім','Өзгеге жанашырлықпен қарап, қамқорлық пен қолдау көрсету.'],['Жауапкершілік','Өз таңдауың мен әрекетіңнің салдарын түсініп, міндетіңді орындау.'],['Ұлағат','Өмірлік тәжірибеден алынған өнеге, тәрбие және жақсы үлгі.'],['Сабақтастық','Құндылық, білім және тәжірибенің ұрпақтан ұрпаққа жалғасуы.']];
const scenarios=[
['Құрмет · цифрлық мәдениет','Досың әлеуметтік желіде ұлттық дәстүр туралы тексерілмеген ақпарат жариялады.','Деректі тексеріп, сыпайы түрде дұрыс ақпарат ұсынамын.','Сенімді дереккөзге сүйену — ақпаратқа да, адамға да құрмет.'],
['Тіл · қолдау','Сыныптасың қазақша сөйлеуге қиналады және қателесуден ұялады.','Оны сынамай, бірге сөйлесуге және жаңа сөздерді бірге үйренуге шақырамын.','Тілдің дамуы қауіпсіз әрі қолдаушы ортадан басталады.'],
['Отбасы · сабақтастық','Ата-әжеңнің бала кезіндегі бір дәстүрі сен үшін қызық болып көрінді.','Ол туралы сұхбат алып, аудио/видео немесе мәтін түрінде сақтаймын.','Отбасылық жадыны сақтау — ұрпақтар сабақтастығына қосқан үлес.'],
['Туған жер · табиғат','Саябақта достарың қоқыс тастап кетті.','Жанжалсыз түсіндіріп, қоқысты бірге жинауды ұсынамын.','Туған жерге сүйіспеншілік нақты әрекеттен көрінеді.'],
['Бірлік · қоғам','Командалық жұмыста бір адамның пікірі үнемі еленбей қалады.','Оның ойын сұрап, ортақ шешімге қосуға тырысамын.','Бірлік — бәрінің бірдей ойлауы емес, бір-бірін тыңдай алуы.'],
['Өнер · мұра','Ұлттық өнер туралы контент жастарға қызықсыз болып көрінеді.','Қысқа бейне, storytelling немесе заманауи визуал арқылы жаңа формат ұсынамын.','Мұраны сақтау мен оны жаңа тілде жеткізу бір-біріне қайшы емес.']
];
let scenarioIndex=0;
const events=[
{date:'2026-09-21',cat:'society',title:'Жастарға арналған волонтерлік кездесу',place:'Қарағанды',time:'17:00',desc:'Жастардың қоғамдық бастамалар мен волонтерлік мүмкіндіктермен танысуы.',source:'https://www.gov.kz/'},
{date:'2026-09-23',cat:'culture',title:'Ұлттық мәдениет туралы ашық кездесу',place:'Қарағанды',time:'15:00',desc:'Ұлттық мәдениет, мұра және жастардың шығармашылық қатысуы.',source:'https://www.gov.kz/'},
{date:'2026-09-26',cat:'nature',title:'Экологиялық сенбілік',place:'Қарағанды',time:'10:00',desc:'Туған өлкені таза ұстауға бағытталған экологиялық бастама.',source:'https://www.gov.kz/'},
{date:'2026-09-27',cat:'culture',title:'Ұлттық өнер күні',place:'Астана',time:'12:00',desc:'Ұлттық өнер мен шығармашылық мұраны таныстыруға арналған мәдени іс-шара.',source:'https://www.gov.kz/'},
{date:'2026-09-30',cat:'society',title:'Жастар идеялары бойынша ашық алаң',place:'Алматы',time:'16:00',desc:'Жастардың әлеуметтік идеяларын талқылауға арналған ашық формат.',source:'https://www.gov.kz/'},
{date:'2026-10-03',cat:'nature',title:'Табиғатты қорғау бастамасы',place:'Қарағанды',time:'11:00',desc:'Қоршаған ортаны қорғауға бағытталған еріктілік шарасы.',source:'https://www.gov.kz/'},
{date:'2026-10-10',cat:'culture',title:'Дәстүр және қазіргі мәдениет кездесуі',place:'Астана',time:'14:00',desc:'Дәстүрдің қазіргі өмірдегі жаңа көріністері туралы пікірталас.',source:'https://www.gov.kz/'},
{date:'2026-10-17',cat:'society',title:'Жастар волонтерлік жәрмеңкесі',place:'Алматы',time:'11:00',desc:'Қоғамдық бастамалар мен волонтерлік ұйымдардың таныстырылымы.',source:'https://www.gov.kz/'}
];
const quiz=[
['Ұлттық құндылық дегенді қалай түсінесің?',['Тек өткен тарихқа қатысты ұғым','Ұлттың рухани, мәдени және әлеуметтік өмірінде маңызды құндылықтар жүйесі','Тек салт-дәстүрлер жиынтығы','Тек ұлттық мерекелер'],'B'],
['«Аманат» ұғымының қазіргі өмірдегі мағынасына қайсысы жақын?',['Біреудің затын уақытша алу','Сеніп тапсырылған нәрсеге жауапкершілікпен қарау','Сыйлық алу','Құпия сақтау ғана'],'B'],
['Досың қазақ тілінде сөйлеуге қиналады. Не істеген дұрыс?',['Онымен сөйлеспеу','Қателескенін күлкі ету','Қолдау көрсетіп, бірге сөйлесуге тырысу','Тек басқа тілде сөйлесу'],'C'],
['«Үлкенге құрмет, кішіге ізет» нені білдіреді?',['Үлкен адамның айтқанын әрқашан орындау','Адамдарға жасына қарамай әдеппен қарау','Тек үлкендермен сөйлесу','Кішілердің пікірін елемеу'],'B'],
['Қай әрекет бірлік құндылығын көрсетеді?',['Барлық шешімді жалғыз қабылдау','Өз пікіріңді ғана дұрыс санау','Командадағы адамдарды тыңдап, ортақ шешімге келу','Бір адамды кінәлау'],'C'],
['«Шаңырақ» нені білдіретін маңызды символдардың бірі?',['Саяхат','Отбасы мен үйдің бірлігі','Байлық','Жеңіс'],'B'],
['Отбасылық дәстүрді сақтаудың ең маңызды жолы?',['Оны ешкімге айтпау','Тек әлеуметтік желіге жариялау','Мәнін түсініп, кейінгі ұрпаққа жеткізу','Өзгеріссіз қайталау ғана'],'C'],
['Ата-әженің әңгімесін жазып алып, отбасы тарихын сақтау қай құндылықпен байланысты?',['Ұрпақтар сабақтастығы','Бәсекелестік','Жеке жетістік','Материалдық байлық'],'A'],
['«Өткеннің өнегесі — ұрпаққа аманат» мәні неде?',['Өткенді өзгеріссіз қайталау','Өткеннен сабақ алып, құнды мұраны болашаққа жеткізу','Тек тарихты жаттау','Ескі дәстүрден бас тарту'],'B'],
['Ұлттық дәстүрді қазіргі заманға бейімдеудің дұрыс мысалы?',['Мәнін түсінбей қайталау','Дәстүрді қолданбау','Негізгі мәнін сақтап, қазіргі өмірде жаңа форматта көрсету','Тек мерекеде еске алу'],'C'],
['Қайсысы ұлттық өнерге жатады?',['Күй','Компьютерлік ойын','Шетелдік сериал','Жарнама'],'A'],
['Домбыраның ұлттық мәдениеттегі орны қандай?',['Тек музыкалық аспап','Қазақтың музыкалық және рухани мұрасының маңызды бөлігі','Тек музей экспонаты','Тек мерекелік зат'],'B'],
['Ұлттық өнерді жастарға қызықты етудің заманауи тәсілі?',['Тек оқулықпен таныстыру','Қысқа видео, подкаст, Reels немесе интерактивті контент','Ақпарат бермеу','Тек үлкендерге арналған формат'],'B'],
['«Бір сөз — бір құндылық» форматының мақсаты?',['Көп сөз жазу','Бір ұлттық ұғымның мағынасын қысқа әрі түсінікті жеткізу','Жарнама жасау','Тек сөздерді жаттату'],'B'],
['Қай сөз ұлттық құндылықтармен тікелей байланысты?',['Аманат','Пароль','Лайк','Контент'],'A'],
['Әлеуметтік желі ұлттық құндылықтарды насихаттауда қалай пайдалы?',['Тек көңіл көтеру үшін','Қысқа әрі қызықты контент тарату арқылы','Тек жарнама үшін','Тек жаңалық оқу үшін'],'B'],
['Ұлттық құндылық туралы қысқа видеоға қай идея тиімді?',['Ұзақ анықтаманы экранға шығару','1 минутта бір дәстүрдің мәнін түсіндіру','Тек мәтін орналастыру','Басқа видеоны көшіру'],'B'],
['Ұлттық контент сапасын арттыру үшін не маңызды?',['Тек көп қаралым','Қызықты формат пен сенімді мазмұнды үйлестіру','Тек трендті қайталау','Көп эмодзи'],'B'],
['«Ұлттық құндылық — тек өткеннің мұрасы» деген пікірге қалай қарайсың?',['Толық дұрыс','Құндылықтар бүгінгі өмірде жаңа формада жалғаса алады','Тек музейде сақталуы керек','Жастарға қатысы жоқ'],'B'],
['«Үлкенге құрмет» әлеуметтік желіде қалай көрінеді?',['Жеке мәліметті рұқсатсыз жариялау','Пікірде әдеп сақтау және адамның ар-намысына құрметпен қарау','Үлкендерді алып тастау','Пікірін елемеу'],'B'],
['Табиғатты қорғау ұлттық құндылықтармен қалай байланысады?',['Туған жерге деген жауапкершіліктің бір көрінісі','Тек экологтардың міндеті','Қатысы жоқ','Тек ауылда маңызды'],'A'],
['«Туған жер» ұғымы нені қамтиды?',['Тек туған қала','Туған өлке, табиғат, халық және мәдениетпен байланыс','Тек географиялық нүкте','Тек туристік орын'],'B'],
['Досың ұлттық мәдениетті мазақтайтын пікір жазды. Не істеген дұрыс?',['Мазақ ету','Жанжал шығару','Сабырмен пікір білдіріп, мәдениетті түрде түсіндіру','Барлығына тарату'],'C'],
['Ұлттық құндылықты жеке өмірде көрсету мысалы?',['Тек ұлттық киім кию','Үлкенге құрмет, отбасыға көмек, ана тілін қолдану','Тек мерекеге қатысу','Постқа лайк басу'],'B'],
['«Менің ұлттық құндылығым» форматында не көрсетуге болады?',['Өзің үшін маңызды құндылық және оның өміріңдегі көрінісі','Тек ұлттық киім суреті','Тек тарихи дата','Басқа адамның пікірі'],'A'],
['Қай әрекет «білу → әрекет ету» қағидасына сәйкес?',['Құрмет туралы видео көру','Анықтаманы жаттау','Үлкен адамға көмектесу және уақыт бөлу','Постқа лайк басу'],'C'],
['Құндылықтың шынайы маңызын қалай түсінуге болады?',['Тек жаттау арқылы','Өмірдегі көрінісін байқап, өз әрекетіңмен көрсету арқылы','Тек тест тапсыру арқылы','Тек әлеуметтік желіден оқу арқылы'],'B'],
['Отбасылық дәстүрді платформаға ұсынсаң, не қосқан дұрыс?',['Атауы ғана','Тарихы, мағынасы және отбасыңда қалай жалғасатыны','Тек суреті','Көшірме мәтін'],'B'],
['Ұлттық құндылықтарды сақтау кімнің ортақ жауапкершілігі?',['Тек тарихшылардың','Тек мұғалімдердің','Тек ата-аналардың','Әр ұрпақтың'],'D'],
['Ұлттық құндылықтың маңызды белгісі қандай?',['Тек өткенде болуы','Тек кітапта жазылуы','Бүгінгі өмірде мәнін сақтап, адам әрекетінен көрінуі','Өзгеріссіз қалуы'],'C']
];
let currentQuiz=0,quizScore=0,currentMonth=new Date(2026,8,1),currentCat='all';
function el(id){return document.getElementById(id)}
function scrollToId(id){el(id)?.scrollIntoView({behavior:'smooth'})}
function openModal(html){el('modalContent').innerHTML=html;el('modal').classList.add('open');el('modal').setAttribute('aria-hidden','false')}
function closeModal(){el('modal').classList.remove('open');el('modal').setAttribute('aria-hidden','true')}
function showToast(t){const x=el('toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2500)}
function toggleMenu(){const n=el('nav');n.style.display=n.style.display==='flex'?'':'flex'}
function renderValues(){el('valueGrid').innerHTML=values.map((v,i)=>`<article class="value-card"><div class="value-index">0${i+1} / 09</div><div class="value-icon">${v.icon}</div><h3>${v.title}</h3><p>${v.text}</p><p class="modern"><b>Бүгін:</b> ${v.modern.replace('Бүгін: ','')}</p><button onclick="valueInfo(${i})">Мағынасын тереңірек ашу →</button></article>`).join('')}
function valueInfo(i){const v=values[i];openModal(`<span class="eyebrow">ҰЛТТЫҚ ҚҰНДЫЛЫҚ · 0${i+1}</span><h2>${v.title}</h2><p>${v.text}</p><div class="choice-result"><b>Қазіргі өмірде:</b><br>${v.modern}</div><h3>Ойлан:</h3><p>Бұл құндылық сенің отбасыңда, достарыңда, оқу ортаңда немесе цифрлық кеңістікте қалай көрінеді?</p><button class="primary" onclick="closeModal();scrollToId('choice')">Өз таңдауымды жасау →</button>`)}
function searchDict(){const q=el('dictInput').value.toLowerCase().trim();const arr=q?dict.filter(x=>(x[0]+' '+x[1]).toLowerCase().includes(q)):dict.slice(0,6);el('dictResults').innerHTML=arr.length?arr.map(x=>`<div class="dict-item"><b>${x[0]}</b><span>${x[1]}</span></div>`).join(''):`<div class="choice-result">«${q}» бойынша QÚNDYLYQ қысқаша сөздігінен нәтиже табылмады. Ресми Termincom базасынан қарап көр.</div>`}
function renderScenario(){const s=scenarios[scenarioIndex%scenarios.length];el('scenarioBox').innerHTML=`<div class="scenario-top"><span>${String((scenarioIndex%scenarios.length)+1).padStart(2,'0')} / ${scenarios.length}</span><span>${s[0]}</span></div><h3>${s[1]}</h3><p>Сен не істер едің?</p><div class="scenario-options"><button onclick="answerScenario('A')"><b>A</b> Елемей өте шығамын.</button><button onclick="answerScenario('B')"><b>B</b> ${s[2]}</button><button onclick="answerScenario('C')"><b>C</b> Бірден басқалардан қолдау сұраймын.</button></div><div id="scenarioResult"></div><button class="light" style="margin-top:16px" onclick="scenarioIndex++;renderScenario()">Келесі жағдай →</button>`}
function answerScenario(a){const good=a==='B';el('scenarioResult').innerHTML=`<div class="choice-result"><b>${good?'Саналы таңдау.':'Ойланып көр:'}</b> ${good?s[3]:'Кейде әрекетсіз қалу мәселені шешпейді. Құндылықты нақты әрекетпен көрсетуге тырыс.'}<br><br><b>Келесі қадам:</b> бүгін осы құндылыққа қатысты бір шағын әрекет жаса.</div>`}
function familyPrompt(t){openModal(`<span class="eyebrow">ОТБАСЫ · ${t}</span><h2>Бір әңгіме — бір мұра</h2><p>Ата-әжеңе немесе ата-анаңа мына сұрақтардың бірін қой:</p><div class="choice-result">«Сіз бала кезіңізде қандай дәстүрді ерекше бағаладыңыз?»<br>«Оның мәні қандай еді?»<br>«Бүгінгі жастар бұл дәстүрді қалай жалғастыра алады?»</div><p>Жауапты аудио, видео немесе мәтін түрінде күнделікке сақта.</p><button class="primary" onclick="closeModal();scrollToId('diary')">Күнделікке жазу →</button>`)}
function openParentSchool(){openModal(`<span class="eyebrow">АТА-АНАЛАР МЕКТЕБІ</span><h2>Құндылықтың бастауы — отбасындағы тәрбие</h2><p>Балаға ұзақ түсіндіруден бұрын, күнделікті әрекет арқылы үлгі көрсету маңызды.</p><div class="choice-result"><b>Бірге жасаңыз:</b><br>1. Отбасылық бір дәстүрді таңдаңыз.<br>2. Оның мәнін балаңызбен талқылаңыз.<br>3. Осы аптада оны бірге орындаңыз.<br>4. «Бүгін біз қандай құндылықты көрсеттік?» деп қорытынды жасаңыз.</div>`)}
function openDiaryDemo(){openModal(`<span class="eyebrow">МЕНІҢ КҮНДЕЛІГІМ</span><h2>Бүгінгі 5 минут</h2><p>Күннің соңында өзіңе есеп бер:</p><div class="choice-result">🎯 Бүгінгі мақсатым?<br>🔎 Не үйрендім?<br>🛠️ Не жасап көрдім?<br>❤️ Не сезіндім және қандай шешім қабылдадым?<br>🌟 Өзіме не үшін алғыс айтамын?</div><button class="primary" onclick="closeModal();scrollToId('diary')">Толық күнделікке өту →</button>`)}
function saveDiary(){const d={goal:el('diaryGoal').value.trim(),learn:el('diaryLearn').value.trim(),action:el('diaryAction').value.trim(),thought:el('diaryThought').value.trim(),date:new Date().toISOString()};if(!d.goal&&!d.learn&&!d.action&&!d.thought){showToast('Кемінде бір жол толтыр.');return}const arr=JSON.parse(localStorage.getItem('q_diary')||'[]');arr.unshift(d);localStorage.setItem('q_diary',JSON.stringify(arr.slice(0,50)));el('diarySaved').textContent='✓ Бүгінгі жазба сақталды';updateMetrics();showToast('Күнделігің сақталды!')}
function saveContribution(){const t=el('contribution').value.trim();if(!t){showToast('Алдымен әрекетіңді жаз.');return}localStorage.setItem('q_contribution',t);el('savedContribution').innerHTML=`<div class="choice-result">✓ Сақталды: ${t}</div>`;updateMetrics();showToast('Менің үлесім сақталды!')}
function newDailyAction(){const a=['Ата-әжеңнен бір отбасы дәстүрінің тарихын сұрап көр.','Қазақ тілінде бір жаңа сөз үйреніп, оны бүгін қолдан.','Туған жеріңдегі бір тарихи орынды зертте.','Бір адамға бүгін әдейі қолдау көрсет.','Ұлттық өнер туралы бір қысқа контент идея жаз.','Табиғатқа пайдалы бір шағын әрекет жаса.'];el('dailyAction').textContent=a[Math.floor(Math.random()*a.length)]}
function ideaPills(){const ideas=['Әжемнің әңгімесі','Бір сөз — бір құндылық','Дәстүрді білесің бе?','Ұлттық өнер — ұрпаққа мұра','Менің ұлттық құндылығым','Туған жерге бір пайдалы іс','Қазақша контенттің бір жаңа форматы'];el('ideaPills').innerHTML=ideas.map(x=>`<button class="idea-pill" onclick="selectIdea('${x.replace(/'/g,"\\'")}')">${x}</button>`).join('')}
function selectIdea(t){el('ideaText').value=t+' — осы идеяны жастарға қызықты форматта дамытқым келеді.';showToast('Идея таңдалды. Енді AI-QUNDY-мен дамыт!')}
function buildIdea(){const raw=el('ideaText').value.trim();if(!raw){showToast('Алдымен идеяңды жаз немесе дайын идеяны таңда.');return}const f=el('ideaFormat').value;const lower=raw.toLowerCase();let value='ұлттық құндылық';if(lower.includes('әже')||lower.includes('отбасы'))value='ұрпақтар сабақтастығы және отбасы';else if(lower.includes('тіл')||lower.includes('қазақ'))value='қазақ тілі';else if(lower.includes('өнер')||lower.includes('домбыра'))value='ұлттық өнер мен мәдени мұра';else if(lower.includes('табиғат')||lower.includes('экология'))value='табиғат және туған жер';else if(lower.includes('дәстүр'))value='салт-дәстүр';let title=raw.replace(/—.*$/,'').trim();if(title.length>48)title=title.slice(0,48)+'…';const scenario=f==='Reels'||f==='Қысқа бейне'?`0–5 сек: назар аудартатын сұрақ.\n5–20 сек: негізгі оқиға/дерек.\n20–40 сек: бүгінгі өмірдегі көрінісі.\n40–55 сек: кейіпкердің немесе автордың жеке ойы.\n55–60 сек: «Ал сен бүгін не істей аласың?» CTA.`:f==='Подкаст'?`Кіріспе: неге бұл тақырып маңызды?\n1-бөлім: негізгі оқиға/ұғым.\n2-бөлім: кейіпкер немесе отбасы тәжірибесі.\n3-бөлім: қазіргі өмірмен байланысы.\nҚорытынды: тыңдарманға бір әрекет.`:f==='YouTube'?`Hook → контекст → кейіпкер/дерек → 3 негізгі ой → қазіргі өмірдегі мысал → көрерменге тапсырма → қорытынды.`:`Кіріспе → негізгі ой → мысал/оқиға → бүгінгі мағына → көрерменге сұрақ.`;const result=`<div class="eyebrow">AI-QUNDY · ИДЕЯ КОНСТРУКТОРЫ</div><div class="result-title">${title}</div><div class="result-block"><b>ҚҰНДЫЛЫҚ</b>${value}</div><div class="result-block"><b>МАҚСАТ</b>Жастарға осы құндылықтың бүгінгі өмірдегі мәнін түсінікті әрі қызықты форматта көрсету.</div><div class="result-block"><b>ЖОСПАР</b>1) Нақты бір оқиға немесе мәселе таңда.<br>2) Бір сенімді дерек немесе кейіпкер тап.<br>3) Құндылықтың мағынасын түсіндір.<br>4) Қазіргі өмірмен байланыстыр.<br>5) Көрерменге нақты әрекет ұсын.</div><div class="result-block"><b>${f.toUpperCase()} СЦЕНАРИЙІ</b>${scenario.replace(/\n/g,'<br>')}</div><div class="result-block"><b>КЕЛЕСІ ҚАДАМ</b>AI-QUNDY-ден «Диалог қос», «Кадрларға бөл», «Hook-ты өзгертіп бер» немесе «3 түрлі нұсқа жаса» деп сұра.</div><button class="primary" onclick="saveIdea('${title.replace(/'/g,"\\'")}')">Идеямды сақтау</button>`;el('ideaResult').innerHTML=result;updateMetrics()}
function saveIdea(title){const arr=JSON.parse(localStorage.getItem('q_ideas')||'[]');arr.unshift({title,date:new Date().toISOString()});localStorage.setItem('q_ideas',JSON.stringify(arr.slice(0,30)));updateMetrics();showToast('Идеяң сақталды!')}
function openAI(){openModal(`<div class="ai-avatar">Q</div><span class="eyebrow">QÚNDYLYQ AI КӨМЕКШІСІ</span><h2>AI-QUNDY</h2><p>Ұлттық құндылық, дәстүр, мәдениет, Сөздік немесе өз идеяң туралы сұра. Мен түсіндіруге, идеяны дамытуға және сценарий құруға көмектесемін.</p><div class="idea-pills"><button class="idea-pill" onclick="aiAsk('Аманат деген не?')">Аманат деген не?</button><button class="idea-pill" onclick="aiAsk('Әжем туралы видеоға сценарий құрастыр')">Әжеме арналған сценарий</button><button class="idea-pill" onclick="aiAsk('Ұлттық өнерге контент идеясы керек')">Ұлттық өнер идеясы</button><button class="idea-pill" onclick="aiAsk('Менің идеямды дамыт')">Идеямды дамыту</button></div><input id="aiInput" placeholder="Сұрағыңды жаз..."><button class="primary" style="margin-top:10px" onclick="aiAsk(el('aiInput').value)">Жауап алу →</button><div id="aiAnswer"></div>`)}
function aiAsk(q){q=(q||'').trim();if(!q)return;let a='';const l=q.toLowerCase();if(l.includes('аманат'))a='Аманат — сеніп тапсырылған жауапкершілік пен мұраны сақтау және келесіге жеткізу ұғымы. Бүгінгі өмірде ол уәдеде тұрудан, отбасылық тарихты сақтаудан және өзіңе сеніп тапсырылған істі жауапкершілікпен орындаудан көрінеді.';else if(l.includes('сценарий'))a='Әрине. Алдымен Hook → негізгі оқиға → құндылықтың мәні → бүгінгі көрініс → жеке ой → әрекетке шақыру құрылымын ұсынамын. Идеяңды «Менің идеям» бөліміндегі конструкторға енгізсең, оны толық сценарийге айналдыра аласың.';else if(l.includes('өнер'))a='Ұлттық өнер үшін «Бұрын → Бүгін → Ертең» форматын қолдан. Мысалы: домбыраның тарихы → қазіргі жас музыкант → 30 секундтық заманауи орындау → көрерменге «Сен ұлттық өнердің қай түрін жалғастырғың келеді?» деген сұрақ.';else if(l.includes('идея'))a='Идеяңды бір сөйлеммен жаз. Мен оны құндылыққа, мақсатқа, аудиторияға, форматқа, жоспарға және сценарийге бөліп дамытуға көмектесемін.';else a='Бұл сұрақты QÚNDYLYQ логикасымен қарастырайық: алдымен ұғымды түсінеміз, оның бүгінгі өмірдегі көрінісін табамыз, содан кейін өзің жасай алатын нақты әрекетті анықтаймыз. Қаласаң, «Менің идеям» бөліміне өтіп, ойыңды бірге дамытайық.';el('aiAnswer').innerHTML=`<div class="choice-result"><b>AI-QUNDY:</b><br>${a}</div>`}
function openSearch(){openModal(`<span class="eyebrow">QÚNDYLYQ ІЗДЕУ</span><h2>Не іздейсің?</h2><input id="globalSearch" autofocus placeholder="Құндылық, дәстүр, сөз, күнделік, идея..." oninput="globalSearch(this.value)"><div id="globalResults" class="dict-results"></div>`)}
function globalSearch(q){q=q.toLowerCase().trim();const all=[...values.map(v=>v.title+' — '+v.text),...dict.map(d=>d[0]+' — '+d[1]),'AI-QUNDY','Ата-әжелер мектебі','Ата-аналар мектебі','Менің күнделігім','Іс жүзінде & менің үлесім','Менің идеям','Quiz 30 сұрақ'];const r=q?all.filter(x=>x.toLowerCase().includes(q)):[];el('globalResults').innerHTML=r.length?r.map(x=>`<div class="dict-item"><span>⌕</span> ${x}</div>`).join(''):(q?'Ештеңе табылмады. Басқа сөзбен іздеп көр.':'Іздеу сөзін енгізіңіз.')}
function openProfile(){const diary=JSON.parse(localStorage.getItem('q_diary')||'[]').length,ideas=JSON.parse(localStorage.getItem('q_ideas')||'[]').length,my=JSON.parse(localStorage.getItem('q_events')||'[]').length,actions=localStorage.getItem('q_contribution')?1:0;openModal(`<span class="eyebrow">МЕНІҢ ПРОФИЛІМ</span><h2>QÚNDYLYQ жолым</h2><div class="contribution-metrics"><div><b>${actions}</b><span>менің әрекетім</span></div><div><b>${my}</b><span>жоспарланған іс-шара</span></div><div><b>${ideas}</b><span>сақталған идея</span></div><div><b>${diary}</b><span>күнделік жазбасы</span></div></div><p>Профильдің толық нұсқасында жетістіктер, таңдаулы материалдар және жеке прогресс көрсетіледі.</p>`)}
function changeMonth(delta){currentMonth=new Date(currentMonth.getFullYear(),currentMonth.getMonth()+delta,1);renderCalendar()}
function renderCalendar(){const y=currentMonth.getFullYear(),m=currentMonth.getMonth();const names=['Жс','Дс','Сс','Ср','Бс','Жм','Сб'];el('monthTitle').textContent=new Intl.DateTimeFormat('kk-KZ',{month:'long',year:'numeric'}).format(currentMonth);let html=names.map(n=>`<div class="cal-head">${n}</div>`).join('');const first=new Date(y,m,1).getDay();const days=new Date(y,m+1,0).getDate();const prevDays=new Date(y,m,0).getDate();for(let i=0;i<42;i++){const d=i-first+1;let date,other=false;if(d<1){date=new Date(y,m-1,prevDays+d);other=true}else if(d>days){date=new Date(y,m+1,d-days);other=true}else date=new Date(y,m,d);const iso=date.toISOString().slice(0,10);const dayEvents=events.filter(e=>e.date===iso&&(currentCat==='all'||e.cat===currentCat));html+=`<div class="cal-day ${other?'other':''}"><div class="day-number">${date.getDate()}</div>${dayEvents.map(e=>{const saved=JSON.parse(localStorage.getItem('q_events')||'[]').includes(e.date+'|'+e.title);return `<div class="event ${e.cat} ${saved?'saved':''}" onclick='eventInfo(${JSON.stringify(e).replace(/'/g,"&#39;")})'><b>${e.title}</b><small>${e.time} · ${e.place}</small></div>`}).join('')}</div>`}el('calendar').innerHTML=html;renderMyEvents()}
function eventInfo(e){const key=e.date+'|'+e.title;const arr=JSON.parse(localStorage.getItem('q_events')||'[]');const saved=arr.includes(key);openModal(`<span class="eyebrow">${e.cat==='nature'?'🌿 ТАБИҒАТ':e.cat==='society'?'🤝 ҚОҒАМ':'🎨 МӘДЕНИЕТ'}</span><h2>${e.title}</h2><p><b>📅 ${e.date}</b> · 🕐 ${e.time}<br>📍 ${e.place}</p><p>${e.desc}</p><div class="choice-result"><b>Ресми дереккөз:</b> іс-шараның нақты уақыты, тіркелу шарты және өзгерістері ұйымдастырушының ресми парақшасынан тексеріледі.</div><div style="display:flex;gap:10px;flex-wrap:wrap;margin-top:18px"><button class="primary" onclick="toggleEvent('${key.replace(/'/g,"\\'")}');closeModal()">${saved?'✓ Менің күнтізбемнен алу':'＋ Менің күнтізбеме қосу'}</button><a class="light linkbtn" target="_blank" rel="noopener" href="${e.source}">Ресми дереккөз →</a></div>`)}
function toggleEvent(key){let arr=JSON.parse(localStorage.getItem('q_events')||'[]');arr=arr.includes(key)?arr.filter(x=>x!==key):[...arr,key];localStorage.setItem('q_events',JSON.stringify(arr));renderCalendar();updateMetrics();showToast(arr.includes(key)?'Іс-шара күнтізбеңе қосылды':'Іс-шара алынды')}
function renderMyEvents(){const arr=JSON.parse(localStorage.getItem('q_events')||'[]');const list=arr.map(k=>{const p=k.split('|');return `<span class="my-event-chip">📅 ${p[0]} · ${p[1]}</span>`}).join('');el('myEventsList').innerHTML=list||'<span style="color:#7a8586;font-size:12px">Әзірге жоспарланған іс-шара жоқ.</span>'}
function updateMetrics(){const diary=JSON.parse(localStorage.getItem('q_diary')||'[]').length,ideas=JSON.parse(localStorage.getItem('q_ideas')||'[]').length,eventsN=JSON.parse(localStorage.getItem('q_events')||'[]').length,actions=localStorage.getItem('q_contribution')?1:0;el('diaryCount').textContent=diary;el('ideaCount').textContent=ideas;el('eventCount').textContent=eventsN;el('actionCount').textContent=actions}
function openQuiz(){currentQuiz=0;quizScore=0;renderQuiz()}
function renderQuiz(){if(currentQuiz>=quiz.length){let badge=quizScore>=27?'Құндылық елшісі':quizScore>=24?'Ұлттық мұра жанашыры':quizScore>=18?'Дәстүр білгірі':quizScore>=11?'Құндылық зерттеушісі':'Құндылыққа қызығушы';openModal(`<span class="eyebrow">QUIZ · НӘТИЖЕ</span><h2>${quizScore}/30 — ${badge}</h2><p>${quizScore>=24?'Сен ұлттық құндылықтардың мағынасын жақсы түсінесің. Енді біліміңді нақты әрекетке айналдырып көр.':quizScore>=18?'Жақсы негіз бар. Құндылықтар мен дәстүрлердің қазіргі өмірдегі көріністерін көбірек зерттеп көр.':'Бұл — бастамасы. Құндылықтар бөлімін, Сөздікті және өмірлік жағдайларды зерттеп, қайта байқап көр.'}</p><div class="choice-result"><b>Келесі қадам:</b> «Менің идеям» бөліміне кіріп, бір құндылықты нақты контентке немесе әрекетке айналдыр.</div><button class="primary" onclick="closeModal();scrollToId('ideas')">Менің идеямды жасау →</button>`);return}const q=quiz[currentQuiz];openModal(`<span class="eyebrow">QUIZ · ${currentQuiz+1}/30</span><h2>${q[0]}</h2>${q[1].map((o,i)=>`<button class="modal-option" onclick="answerQuiz('${String.fromCharCode(65+i)}')"><b>${String.fromCharCode(65+i)}</b> — ${o}</button>`).join('')}`)}
function answerQuiz(a){if(a===quiz[currentQuiz][2])quizScore++;currentQuiz++;renderQuiz()}
document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentCat=b.dataset.cat;renderCalendar()}));
window.addEventListener('load',()=>{renderValues();ideaPills();renderScenario();searchDict();renderCalendar();updateMetrics();const c=localStorage.getItem('q_contribution');if(c)el('savedContribution').innerHTML=`<div class="choice-result">✓ Бұрынғы жазба: ${c}</div>`});
